name: BurnedAreaAttribution
channels:
  - conda-forge
  - defaults
dependencies:
  - iris=3.4.0
  - pandas=1.5.3
  - regionmask=0.9.0
  - seaborn=0.12.2
  - numpy=1.24.2
  - cf-units=3.1.1
  - geopandas=0.12.2
  - python=3.11.0
  - cftime=1.6.2
  - matplotlib=3.7.0
  - jupyterlab=3.6.1
  - scipy=1.10.0
  - xarray=2023.2.0
  - cartopy=0.21.1
  - openpyxl=3.1.2
